name: Project CI

on:
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        java: ['11']

    name: Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: maven
      - name: Check license hearders
        run: ./mvnw license:check

      - name: Check NOTICE
        run: ./mvnw -B notice:check

      - name: Build backend
        run: ./mvnw -B package --file pom.xml
